INSERT INTO tblCategory
	(cat_name)
VALUES
	('Fresh Cuts'),
	('Sausages');
	
INSERT INTO tblProducts
	(prod_name, prod_weight, prod_price, prod_description, prod_image, tblCategory_cat_id)
VALUES
	('Baby Back Ribs', '2.5 lbs', '$20.00', 'A hardy rib loaded with meat. This fall off the bone pork will ensure you are the king at any BBQ.  Approx. 2.5 lbs each package.  This full rack of ribs can feed up to 4 people.  Local meat grown & prepared in Victoria B.C.', 'http://deepblue.camosun.bc.ca/~cst634/images/Back_rib_image_256.jpg', 1),
	('Pork Hock', '2.4 lbs', '$10.00', 'From our shop to your stock! Filled with plenty of gelatin and flavor, perfect for your homemade soup stock. Approx. 2.4 lbs. / package.  Berryman Farms pasture raised pork.  Local meat grown & prepared in Victoria B.C.', 'http://deepblue.camosun.bc.ca/~cst634/images/pork_hock_256.jpg', 1),
	('Bone-in-Loin Chops', '1 lb', '$12.00', 'Move on over veggies. Here comes the MEAT. Sink your teeth into these juicy bone in pork chops. Season, grill and enjoy. The bone adds amazing flavor to the lean loin when cooked over a hot grill.  Each chop is approx. 8 oz.  2 bone in pork chops / package.  Berryman Farms pasture raised pork.  Local Meat grown & prepared in Victoria B.C.', 'http://deepblue.camosun.bc.ca/~cst634/images/bone_in_loin_chop_256.jpg', 1),
	('Bone-in-Shoulder/Butt Roast', '3 lbs', '$20.00', 'The Shoulder roast is the best cut for your amazing pulled pork. Cook it right and you can pull the meat off the bone with a fork. Blend your shredded shoulder with your self proclaimed "worlds best" BBQ sauce and you will then have the worlds best pulled pork.  Approx. 3 Lbs.  Berryman Farms pastures raised pork.  Local Meat grown & prepared in Victoria B.C.', 'http://deepblue.camosun.bc.ca/~cst634/images/shoulder-butt_bone_in_roast_256.jpg', 1),
	('Shoulder/Butt Steaks', '2 lbs', '$15.00', 'These bone in shoulder steaks are best cooked low and slow. Thick cut and great on the BBQ. Marinate before cooking in your favorite flavors.  Approx. 1 lb each steak.  2 steaks/package.  Berryman Farms pasture raised pork.  Local Meat grown & prepared in Victoria B.C.', 'http://deepblue.camosun.bc.ca/~cst634/images/shoulder-butt_steak_256.jpg', 1),
	('Boneless Sirloin Steak', '1 lb', '$12.00', 'These juicy steaks are hard to come by; tender and extremely lean. Grab yours while you can there is only 6 steaks on each animal! Approx. 0.5 lb each.  2 steaks / package.  Berryman Farms pasture raised pork.  Local Meat grown & prepared in Victoria B.C.', 'http://deepblue.camosun.bc.ca/~cst634/images/boneless_sirloin_steak_256.jpg', 1),
	('Pork Belly Slab', '1.5 lbs', '$12.00', 'Pork belly is a boneless cut of meat from the belly of a pig. This cut of meat is popular in East Asian, European, and North American cuisine. Also used for BACON!  Approx. 1.5 lbs each package.  Berryman  Farms pasture raised pork.  Local Meat grown & Prepared in Victoria B.C.', 'http://deepblue.camosun.bc.ca/~cst634/images/pork_belly_256.jpg', 1),
	('Lean Ground Pork', '1 lb', '$5.00', 'Lean and finely ground, great for burgers, meat balls, Meat loaf, or well anything you can imaging.  Berryman Farms pasture raised pork.  Local Meat grown & prepared in Victoria B.C.', 'http://deepblue.camosun.bc.ca/~cst634/images/lean_ground_pork_256.jpg', 1),
	('Boneless Loin Chops', '1 lb', '$12.00', 'Berryman Farms Boneless pork chops are a fan favorite. Easy to sear, grill, and bake.  Each chop is approx. 0.33 lb.  3 boneless pork chops / package.  Berryman Farms pasture raised pork.  Local  Meat grown & prepared in Victoria B.C.', 'http://deepblue.camosun.bc.ca/~cst634/images/boneless_loin_chop_256.jpg', 1),
	('Boneless Loin Roast', '2.5 lbs', '$20.00', 'Take you secret family recipe to the next level. Apply your secret spice blend or rub to this extremely lean and flavorful boneless pork loin roast. Bake in the oven until the internal temperature reads 145 degrees F. let the roast sit for 5 - 10 mins slice and serve. The end result will be a juicy roast for the family to enjoy.  Great for any type of family gatherings or Sunday dinner.  1 Boneless loin roast approx. 2.5 lbs.  Berryman Farms pasture raised pork.  Local Meat grown & prepared in Victoria B.C.', 'http://deepblue.camosun.bc.ca/~cst634/images/loin_roast_256.jpg', 1),
	('Boneless Shoulder/Butt Roast', '3 lbs', '$25.00', 'An easy carving option when it comes to the shoulder roast. Cook Low and slow and slice it or shred it apart for pulled pork. Succulent and juicy!  Approx. 3 lbs.  Berryman Farms pasture raised pork.  Local Meat grown & prepared in Victoria B.C.', 'http://deepblue.camosun.bc.ca/~cst634/images/boneless_shoulder_butt_roast_256.jpg', 1),
	('Side Ribs', '1 lb', '$10.00', 'These are taken from the belly side of the rib cage below the back ribs. They are flat, and contain more bone and fat than meat. Because of the fat, they are more tender than back ribs, but will take a longer time to cook.  1 full rack split in half/package.  Approx. 1 Lb.  Berryman Farms pasture raised pork.  Local Meat grown & prepared in Victoria B.C.', 'http://deepblue.camosun.bc.ca/~cst634/images/side_ribs_256.jpg', 1),
	('Canadian Maple Sausage', '1 lb', '$7.00', 'Maple syrup infused sausage, perfect addition to any breakfast or appetizer platter. Kids love them!  Ingredients: Gluten Free!  Berryman Farms pasture raised pork.  Sea Salt, Black Pepper, Maple Sugar, Corn Starch.  All sausages are packaged in approx. 1 lb packages.  Local meat grown & prepared in Victoria B.C.', 'http://deepblue.camosun.bc.ca/~cst634/images/maple_sausage_256.jpg', 2),
	('German Bratwurst Sausage', '1 lb', '$7.00', 'The historic Bratwurst sausage, is flavorful and perfect for any occasion.   Famous in Germany and is becoming very popular in the western countries today. Great for picnics and barbecues. Help us make our Bratwurst world famous!  Ingredients: Gluten Free!  Berryman Farms pasture raised pork.  Sea Salt, White Pepper, Garlic, Mace, Thyme.  All sausages are packaged in approx. 1 lb packages.  Local meat grown & prepared in Victoria B.C.', 'http://deepblue.camosun.bc.ca/~cst634/images/german_bratwurst_256.jpg', 2),
	('Hot Italian Sausage', '1 lb', '$7.00', 'The unique flavor of fennel seed, accompanied by the heat of a cayenne pepper, It is HOT!  Ingredients: Gluten Free!  Berryman Farms pasture raised pork.  Sea Salt, Black Pepper, Garlic, Fennel Seed, Chilies, Cayenne Pepper, Anise Seed.  All sausages are packaged in approx. 1 lb packages.  Local meat grown & Prepared in Victoria B.C.', 'http://deepblue.camosun.bc.ca/~cst634/images/italian_sausage_256.jpg', 2),
	('Mild Italian Sausage', '1 lb', '$7.00', 'The unique flavor of fennel seed accompanied by a touch of heat from chili peppers. Medium heat level. Delicious on its own, or great for homemade pasta sauces.  Ingredients: Gluten Free!  Berryman Farms pasture raised pork.  Sea Salt, Black Pepper, Garlic, Fennel Seed, Chilies, Anise Seed.  All sausages are packaged in approx. 1 lb packages.  Local meat grown & prepared in Victoria B.C.', 'http://deepblue.camosun.bc.ca/~cst634/images/italian_sausage_256.jpg', 2),
	('Spanish Chorizo Sausage', '1 lb', '$7.00', 'A fresh Spanish chorizo is a special blend dating back to the roman times. Sink your teeth into this sausage right off the grill or slice it and place it in a beautiful fresh pasta sauce.  Ingredients: Gluten Free!  Berryman Farms pasture raised pork.  Sea Salt, Black Pepper, Onion, Garlic, Paprika, Chilie pepper.  All sausages are packaged in approx. 1 lb packages.  Local Meat grown & Prepared in Victoria B.C.', 'http://deepblue.camosun.bc.ca/~cst634/images/spanish_chorizo_256.jpg', 2),
	('Sweet Apple Cranberry Sausage', '1 lb', '$7.00', 'Let your taste buds relax with this mouth watering sweet sausage. Crisp and crunchy granny smith apples mixed with sweet cranberries accompanied by a touch of seasoning.  Ingredients: Gluten Free!  Berryman Farms pasture raised pork.  Salt, Herbs de Province, Granny Smith apples, dried cranberries.  All sausages are packaged in approx. 1lb packages.  Local Meat grown & prepared in Victoria B.C.', 'http://deepblue.camosun.bc.ca/~cst634/images/sweet_apple_cranberry_256.jpg', 2),
	('Honey Garlic Sausage', '1 lb', '$7.00', 'Sweet and savory.  This Honey Garlic sausage is great anytime. Perfect for barbecuing and serving up on a bun!  Ingredients: Gluten Free!  Berryman farms pasture raised pork.  Sea Salt, Black Pepper, Garlic, Unpasteurized honey.  All sausages are packaged in approx. 1 lb packages.  Local meat grown & prepared in Victoria B.C.', 'http://deepblue.camosun.bc.ca/~cst634/images/honey_garlic_256.jpg', 2),
	('Coconut Curry Sausage', '1 lb', '$7.00', 'A delicious taste of India infused into our gourmet pork sausage.  This curry flavored sausage is one of our top sellers, and for good reason.  One taste of this mouth watering recipe and you will wish you had bought more!  Ingredients: Gluten Free!  Berryman Farms pasture raised pork.  Sea Salt, Black Pepper, Garlic, Curry Powder.  All sausages are packaged in approx. 1 lb packages.  Local meat grown & prepared in Victoria B.C.', 'http://deepblue.camosun.bc.ca/~cst634/images/coconut_curry_256.jpg', 2),
	('Breakfast Sausage', '1 lb', '$7.00', 'Try our signature breakfast sausage. You will never go back to another breakfast sausage again. A combination of spices like no other.  Ingredients: Gluten Free!  Berryman Farms pasture raised pork.  Sea Salt, Black Pepper, Onion Powder, Nutmeg, Sage.  All sausages are packaged in approx. 1 lb packages.  Local Meat grown & prepared in Victoria B.C.', 'http://deepblue.camosun.bc.ca/~cst634/images/breakfast_sausage_256.jpg', 2),
	('Crunchy Kale & Cow Feta Sausage', '1 lb', '$9.00', 'Elegance and bliss placed gently into a sausage. The new super food Crunchy Kale combined with a deep rich cow feta will leave your mouth watering.  Ingredients: Gluten Free!  Berryman Farms pasture raised pork.  Sea Salt, Black Pepper, Garlic, Onion, Crunchy Kale, Cow Feta.  All sausages are packaged in approx. 1 lb packages.  Local meat grown & prepared in Victoria B.C.', 'http://deepblue.camosun.bc.ca/~cst634/images/fresh_crunchy_kale_cow_feta_sausage_256.jpg', 2),
	('Portebella & Monterey Jack Sausage', '1 lb', '$9.00', 'This new Dinner sausage will enhance any dish with its bold flavor and did we mention cheese......  Ingredients: Sea Salt, Black Pepper, Garlic, Portobello Mushrooms, Monterey Jack Cheddar cheese.  All sausages are packaged in approx. 1 lb packages.  Local Meat grown & prepared in Victoria B.C.', 'http://deepblue.camosun.bc.ca/~cst634/images/protabella_monterey_jack_sausage_256.jpg', 2),
	('Jalapeno & Smoke Cheddar Sausage', '1 lb', '$9.00', 'Juicy Jalapenos and extra old cheddar cheese lends just the right balance of heat to be interesting, but not overly spicy. This sausage was created for my addiction to jalapenos.  Ingredients: Berryman Farms pasture raised pork.  Sea Salt, Black Pepper, Garlic, Chilies, Cayenne Pepper, Fresh Jalapenos, Extra old cheddar cheese.  All sausages are packaged in approx. 1 lb packages.  Local meat grown & prepared in Victoria B.C.', 'http://deepblue.camosun.bc.ca/~cst634/images/jalapeno_chedder_sausage_256.jpg', 2),
	('Sundried Tomato Spinach & Feta Sausage', '1 lb', '$9.00', 'A delicious taste of the mediterranean infused into our gourmet pork sausage.  The flavours in this sausage come through so beautifully, if you close your eyes, you might even feel like you are sailing the Greek Isles!  Ingredients: Gluten Free!  Berryman Farms pasture raised pork.  Sea Salt, Black Pepper, Onion, Paprika, Sundried tomato, Feta cheese, Spinach.  All sausages are packaged in approx. 1 lb packages.  Local meat grown & prepared in Victoria B.C.', 'http://deepblue.camosun.bc.ca/~cst634/images/sundried_tomato_spinach_feta_sausage_256.jpg', 2);

